# Site settings
title: Alan Berotti
email: alanberotti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website for Alan Berotti
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Alan Berotti
email: alanberotti@gmail.com
linkedin_username: beroa
github_username: beroa

# API settings
google_api_key:

# Build settings
markdown: kramdown